import { createEffect, createStore, sample } from 'effector';
import { useUnit } from 'effector-react';

import { MunzenCurrency } from './types';

const $munzenCurrencies = createStore<MunzenCurrency[] | null>(null);

const fetchMunzenCurrenciesFx = createEffect<void, MunzenCurrency[], null>(() => {
  return new Promise(resolve => {
    setTimeout(() => {
      resolve([
        {
          id: 67,
          ticker: 'USDT',
          viewedTicker: 'USDT',
          name: 'Tether',
          isCrypto: true,
          blockchainNetwork: 'TRC20',
          tickerWithNetwork: 'USDT-TRC20',
          logoUrl:
            'https://widget-backend.prod.gcp.munzen.io/storage/images/currencies/crypto/usdt.svg',
          priority: 0,
          isBestConditions: false,
          decimals: 6,
          roundOff: 6,
          description: null,
          tooltipDescription: null,
          discountDescription: null,
          feeValue: null,
        },
        {
          id: 74,
          ticker: 'FTN',
          viewedTicker: 'FTN',
          name: 'Fasttoken',
          isCrypto: true,
          blockchainNetwork: 'BAHAMUT',
          tickerWithNetwork: 'FTN-BAHAMUT',
          logoUrl:
            'https://widget-backend.prod.gcp.munzen.io/storage/images/currencies/crypto/ftn.svg',
          priority: 0,
          isBestConditions: false,
          decimals: 6,
          roundOff: 6,
          description: null,
          tooltipDescription: null,
          discountDescription: null,
          feeValue: null,
        },
        {
          id: 65,
          ticker: 'BNB',
          viewedTicker: 'BNB',
          name: 'BNB (Binance coin)',
          isCrypto: true,
          blockchainNetwork: 'BEP20',
          tickerWithNetwork: 'BNB',
          logoUrl:
            'https://widget-backend.prod.gcp.munzen.io/storage/images/currencies/crypto/bnb.svg',
          priority: 0,
          isBestConditions: false,
          decimals: 26,
          roundOff: 10,
          description: null,
          tooltipDescription: null,
          discountDescription: null,
          feeValue: null,
        },
        {
          id: 71,
          ticker: 'USDT',
          viewedTicker: 'USDT',
          name: 'Tether',
          isCrypto: true,
          blockchainNetwork: 'AURORA',
          tickerWithNetwork: 'USDT-AURORA',
          logoUrl:
            'https://widget-backend.prod.gcp.munzen.io/storage/images/currencies/crypto/usdt.svg',
          priority: 0,
          isBestConditions: false,
          decimals: 6,
          roundOff: 6,
          description: null,
          tooltipDescription: null,
          discountDescription: null,
          feeValue: null,
        },
        {
          id: 72,
          ticker: 'USDC',
          viewedTicker: 'USDC',
          name: 'USD Coin',
          isCrypto: true,
          blockchainNetwork: 'AURORA',
          tickerWithNetwork: 'USDC-AURORA',
          logoUrl:
            'https://widget-backend.prod.gcp.munzen.io/storage/images/currencies/crypto/usdc.svg',
          priority: 0,
          isBestConditions: false,
          decimals: 6,
          roundOff: 6,
          description: null,
          tooltipDescription: null,
          discountDescription: null,
          feeValue: null,
        },
        {
          id: 16,
          ticker: 'INR',
          viewedTicker: 'INR',
          name: 'Indian Rupee',
          isCrypto: false,
          blockchainNetwork: null,
          tickerWithNetwork: 'INR',
          logoUrl:
            'https://widget-backend.prod.gcp.munzen.io/storage/images/currencies/fiat/inr.svg',
          priority: 0,
          isBestConditions: false,
          decimals: 2,
          roundOff: 2,
          description: null,
          tooltipDescription: null,
          discountDescription: null,
          feeValue: null,
        },
        {
          id: 66,
          ticker: 'USDT',
          viewedTicker: 'USDT',
          name: 'Tether',
          isCrypto: true,
          blockchainNetwork: 'BEP20',
          tickerWithNetwork: 'USDT-BEP20',
          logoUrl:
            'https://widget-backend.prod.gcp.munzen.io/storage/images/currencies/crypto/usdt.svg',
          priority: 0,
          isBestConditions: false,
          decimals: 18,
          roundOff: 6,
          description: null,
          tooltipDescription: null,
          discountDescription: null,
          feeValue: null,
        },
        {
          id: 73,
          ticker: 'FTN',
          viewedTicker: 'FTN',
          name: 'Fasttoken',
          isCrypto: true,
          blockchainNetwork: 'ERC20',
          tickerWithNetwork: 'FTN-ERC20',
          logoUrl:
            'https://widget-backend.prod.gcp.munzen.io/storage/images/currencies/crypto/ftn.svg',
          priority: 0,
          isBestConditions: false,
          decimals: 6,
          roundOff: 6,
          description: null,
          tooltipDescription: null,
          discountDescription: null,
          feeValue: null,
        },
        {
          id: 77,
          ticker: 'LTC',
          viewedTicker: 'LTC',
          name: 'Litecoin',
          isCrypto: true,
          blockchainNetwork: 'LTC',
          tickerWithNetwork: 'LTC',
          logoUrl:
            'https://widget-backend.prod.gcp.munzen.io/storage/images/currencies/crypto/ltc.svg',
          priority: 0,
          isBestConditions: false,
          decimals: 8,
          roundOff: 8,
          description: null,
          tooltipDescription: null,
          discountDescription: null,
          feeValue: null,
        },
        {
          id: 32,
          ticker: 'ETH',
          viewedTicker: 'ETH',
          name: 'Ethereum',
          isCrypto: true,
          blockchainNetwork: 'ERC20',
          tickerWithNetwork: 'ETH',
          logoUrl:
            'https://widget-backend.prod.gcp.munzen.io/storage/images/currencies/crypto/eth.svg',
          priority: 0,
          isBestConditions: false,
          decimals: 18,
          roundOff: 8,
          description: null,
          tooltipDescription: null,
          discountDescription: null,
          feeValue: null,
        },
        {
          id: 78,
          ticker: 'BCH',
          viewedTicker: 'BCH',
          name: 'Bitcoin Cash',
          isCrypto: true,
          blockchainNetwork: 'BCH',
          tickerWithNetwork: 'BCH',
          logoUrl:
            'https://widget-backend.prod.gcp.munzen.io/storage/images/currencies/crypto/bch.svg',
          priority: 0,
          isBestConditions: false,
          decimals: 8,
          roundOff: 8,
          description: null,
          tooltipDescription: null,
          discountDescription: null,
          feeValue: null,
        },
        {
          id: 8,
          ticker: 'BRL',
          viewedTicker: 'BRL',
          name: 'Brazilian Real',
          isCrypto: false,
          blockchainNetwork: null,
          tickerWithNetwork: 'BRL',
          logoUrl:
            'https://widget-backend.prod.gcp.munzen.io/storage/images/currencies/fiat/brl.svg',
          priority: 0,
          isBestConditions: false,
          decimals: 2,
          roundOff: 2,
          description: null,
          tooltipDescription: null,
          discountDescription: null,
          feeValue: null,
        },
        {
          id: 1,
          ticker: 'USD',
          viewedTicker: 'USD',
          name: 'United States Dollar',
          isCrypto: false,
          blockchainNetwork: null,
          tickerWithNetwork: 'USD',
          logoUrl:
            'https://widget-backend.prod.gcp.munzen.io/storage/images/currencies/fiat/usd.svg',
          priority: 0,
          isBestConditions: false,
          decimals: 2,
          roundOff: 2,
          description: null,
          tooltipDescription: null,
          discountDescription: null,
          feeValue: null,
        },
        {
          id: 2,
          ticker: 'EUR',
          viewedTicker: 'EUR',
          name: 'Euro',
          isCrypto: false,
          blockchainNetwork: null,
          tickerWithNetwork: 'EUR',
          logoUrl:
            'https://widget-backend.prod.gcp.munzen.io/storage/images/currencies/fiat/eur.svg',
          priority: 0,
          isBestConditions: false,
          decimals: 2,
          roundOff: 2,
          description: null,
          tooltipDescription: null,
          discountDescription: null,
          feeValue: null,
        },
        {
          id: 17,
          ticker: 'ISK',
          viewedTicker: 'ISK',
          name: 'Icelandic Krona',
          isCrypto: false,
          blockchainNetwork: null,
          tickerWithNetwork: 'ISK',
          logoUrl:
            'https://widget-backend.prod.gcp.munzen.io/storage/images/currencies/fiat/isk.svg',
          priority: 0,
          isBestConditions: false,
          decimals: 0,
          roundOff: 0,
          description: null,
          tooltipDescription: null,
          discountDescription: null,
          feeValue: null,
        },
        {
          id: 5,
          ticker: 'CAD',
          viewedTicker: 'CAD',
          name: 'Canadian Dollar',
          isCrypto: false,
          blockchainNetwork: null,
          tickerWithNetwork: 'CAD',
          logoUrl:
            'https://widget-backend.prod.gcp.munzen.io/storage/images/currencies/fiat/cad.svg',
          priority: 0,
          isBestConditions: false,
          decimals: 2,
          roundOff: 2,
          description: null,
          tooltipDescription: null,
          discountDescription: null,
          feeValue: null,
        },
        {
          id: 7,
          ticker: 'ARS',
          viewedTicker: 'ARS',
          name: 'Argentine Peso',
          isCrypto: false,
          blockchainNetwork: null,
          tickerWithNetwork: 'ARS',
          logoUrl:
            'https://widget-backend.prod.gcp.munzen.io/storage/images/currencies/fiat/ars.svg',
          priority: 0,
          isBestConditions: false,
          decimals: 2,
          roundOff: 2,
          description: null,
          tooltipDescription: null,
          discountDescription: null,
          feeValue: null,
        },
        {
          id: 20,
          ticker: 'MXN',
          viewedTicker: 'MXN',
          name: 'Mexican Peso',
          isCrypto: false,
          blockchainNetwork: null,
          tickerWithNetwork: 'MXN',
          logoUrl:
            'https://widget-backend.prod.gcp.munzen.io/storage/images/currencies/fiat/mxn.svg',
          priority: 0,
          isBestConditions: false,
          decimals: 2,
          roundOff: 2,
          description: null,
          tooltipDescription: null,
          discountDescription: null,
          feeValue: null,
        },
        {
          id: 11,
          ticker: 'COP',
          viewedTicker: 'COP',
          name: 'Colombian Peso',
          isCrypto: false,
          blockchainNetwork: null,
          tickerWithNetwork: 'COP',
          logoUrl:
            'https://widget-backend.prod.gcp.munzen.io/storage/images/currencies/fiat/cop.svg',
          priority: 0,
          isBestConditions: false,
          decimals: 2,
          roundOff: 2,
          description: null,
          tooltipDescription: null,
          discountDescription: null,
          feeValue: null,
        },
        {
          id: 31,
          ticker: 'BTC',
          viewedTicker: 'BTC',
          name: 'Bitcoin',
          isCrypto: true,
          blockchainNetwork: 'BTC',
          tickerWithNetwork: 'BTC',
          logoUrl:
            'https://widget-backend.prod.gcp.munzen.io/storage/images/currencies/crypto/btc.svg',
          priority: 0,
          isBestConditions: false,
          decimals: 8,
          roundOff: 8,
          description: null,
          tooltipDescription: null,
          discountDescription: null,
          feeValue: null,
        },
        {
          id: 41,
          ticker: 'USDT',
          viewedTicker: 'USDT',
          name: 'Tether',
          isCrypto: true,
          blockchainNetwork: 'ERC20',
          tickerWithNetwork: 'USDT-ERC20',
          logoUrl:
            'https://widget-backend.prod.gcp.munzen.io/storage/images/currencies/crypto/usdt.svg',
          priority: 0,
          isBestConditions: false,
          decimals: 6,
          roundOff: 6,
          description: null,
          tooltipDescription: null,
          discountDescription: null,
          feeValue: null,
        },
        {
          id: 70,
          ticker: 'FUN',
          viewedTicker: 'FUN',
          name: 'Fun Token',
          isCrypto: true,
          blockchainNetwork: 'ERC20',
          tickerWithNetwork: 'FUN-ERC20',
          logoUrl:
            'https://widget-backend.prod.gcp.munzen.io/storage/images/currencies/crypto/fun.svg',
          priority: 0,
          isBestConditions: false,
          decimals: 8,
          roundOff: 8,
          description: null,
          tooltipDescription: null,
          discountDescription: null,
          feeValue: null,
        },
        {
          id: 30,
          ticker: 'NEAR',
          viewedTicker: 'NEAR',
          name: 'NEAR Protocol',
          isCrypto: true,
          blockchainNetwork: 'NEAR',
          tickerWithNetwork: 'NEAR',
          logoUrl:
            'https://widget-backend.prod.gcp.munzen.io/storage/images/currencies/crypto/near.svg',
          priority: 0,
          isBestConditions: true,
          decimals: 24,
          roundOff: 8,
          description: null,
          tooltipDescription: null,
          discountDescription: '',
          feeValue: 0.0002,
        },
        {
          id: 35,
          ticker: 'AVAX',
          viewedTicker: 'AVAX',
          name: 'Avalanche C-Chain',
          isCrypto: true,
          blockchainNetwork: 'AVAX',
          tickerWithNetwork: 'AVAX',
          logoUrl:
            'https://widget-backend.prod.gcp.munzen.io/storage/images/currencies/crypto/avax.svg',
          priority: 0,
          isBestConditions: false,
          decimals: 18,
          roundOff: 8,
          description: null,
          tooltipDescription: null,
          discountDescription: null,
          feeValue: null,
        },
        {
          id: 63,
          ticker: 'USDT',
          viewedTicker: 'USDT',
          name: 'Tether',
          isCrypto: true,
          blockchainNetwork: 'MATIC',
          tickerWithNetwork: 'USDT-MATIC',
          logoUrl:
            'https://widget-backend.prod.gcp.munzen.io/storage/images/currencies/crypto/usdt.svg',
          priority: 0,
          isBestConditions: false,
          decimals: 6,
          roundOff: 6,
          description: null,
          tooltipDescription: null,
          discountDescription: null,
          feeValue: null,
        },
        {
          id: 3,
          ticker: 'GBP',
          viewedTicker: 'GBP',
          name: 'British Pound Sterling',
          isCrypto: false,
          blockchainNetwork: null,
          tickerWithNetwork: 'GBP',
          logoUrl:
            'https://widget-backend.prod.gcp.munzen.io/storage/images/currencies/fiat/gbp.svg',
          priority: 0,
          isBestConditions: false,
          decimals: 2,
          roundOff: 2,
          description: null,
          tooltipDescription: null,
          discountDescription: null,
          feeValue: null,
        },
        {
          id: 9,
          ticker: 'CHF',
          viewedTicker: 'CHF',
          name: 'Swiss Franc',
          isCrypto: false,
          blockchainNetwork: null,
          tickerWithNetwork: 'CHF',
          logoUrl:
            'https://widget-backend.prod.gcp.munzen.io/storage/images/currencies/fiat/chf.svg',
          priority: 0,
          isBestConditions: false,
          decimals: 2,
          roundOff: 2,
          description: null,
          tooltipDescription: null,
          discountDescription: null,
          feeValue: null,
        },
        {
          id: 25,
          ticker: 'SEK',
          viewedTicker: 'SEK',
          name: 'Swedish Krona',
          isCrypto: false,
          blockchainNetwork: null,
          tickerWithNetwork: 'SEK',
          logoUrl:
            'https://widget-backend.prod.gcp.munzen.io/storage/images/currencies/fiat/sek.svg',
          priority: 0,
          isBestConditions: false,
          decimals: 2,
          roundOff: 2,
          description: null,
          tooltipDescription: null,
          discountDescription: null,
          feeValue: null,
        },
        {
          id: 24,
          ticker: 'PLN',
          viewedTicker: 'PLN',
          name: 'Polish Zloty',
          isCrypto: false,
          blockchainNetwork: null,
          tickerWithNetwork: 'PLN',
          logoUrl:
            'https://widget-backend.prod.gcp.munzen.io/storage/images/currencies/fiat/pln.svg',
          priority: 0,
          isBestConditions: false,
          decimals: 2,
          roundOff: 2,
          description: null,
          tooltipDescription: null,
          discountDescription: null,
          feeValue: null,
        },
        {
          id: 22,
          ticker: 'NOK',
          viewedTicker: 'NOK',
          name: 'Norwegian Krone',
          isCrypto: false,
          blockchainNetwork: null,
          tickerWithNetwork: 'NOK',
          logoUrl:
            'https://widget-backend.prod.gcp.munzen.io/storage/images/currencies/fiat/nok.svg',
          priority: 0,
          isBestConditions: false,
          decimals: 2,
          roundOff: 2,
          description: null,
          tooltipDescription: null,
          discountDescription: null,
          feeValue: null,
        },
        {
          id: 13,
          ticker: 'DKK',
          viewedTicker: 'DKK',
          name: 'Danish Krone',
          isCrypto: false,
          blockchainNetwork: null,
          tickerWithNetwork: 'DKK',
          logoUrl:
            'https://widget-backend.prod.gcp.munzen.io/storage/images/currencies/fiat/dkk.svg',
          priority: 0,
          isBestConditions: false,
          decimals: 2,
          roundOff: 2,
          description: null,
          tooltipDescription: null,
          discountDescription: null,
          feeValue: null,
        },
        {
          id: 12,
          ticker: 'CZK',
          viewedTicker: 'CZK',
          name: 'Czech Koruna',
          isCrypto: false,
          blockchainNetwork: null,
          tickerWithNetwork: 'CZK',
          logoUrl:
            'https://widget-backend.prod.gcp.munzen.io/storage/images/currencies/fiat/czk.svg',
          priority: 0,
          isBestConditions: false,
          decimals: 2,
          roundOff: 2,
          description: null,
          tooltipDescription: null,
          discountDescription: null,
          feeValue: null,
        },
        {
          id: 69,
          ticker: 'MATIC',
          viewedTicker: 'MATIC',
          name: 'Polygon',
          isCrypto: true,
          blockchainNetwork: 'MATIC',
          tickerWithNetwork: 'MATIC',
          logoUrl:
            'https://widget-backend.prod.gcp.munzen.io/storage/images/currencies/crypto/matic.svg',
          priority: 0,
          isBestConditions: false,
          decimals: 18,
          roundOff: 6,
          description: null,
          tooltipDescription: null,
          discountDescription: null,
          feeValue: null,
        },
        {
          id: 61,
          ticker: 'AURORA',
          viewedTicker: 'AURORA',
          name: 'Aurora',
          isCrypto: true,
          blockchainNetwork: 'AURORA',
          tickerWithNetwork: 'AURORA-AURORA',
          logoUrl:
            'https://widget-backend.prod.gcp.munzen.io/storage/images/currencies/crypto/aurora.svg',
          priority: 0,
          isBestConditions: false,
          decimals: 26,
          roundOff: 6,
          description: null,
          tooltipDescription: null,
          discountDescription: null,
          feeValue: null,
        },
      ]);
    }, 1000);
  });
});

sample({
  clock: fetchMunzenCurrenciesFx.doneData,
  target: $munzenCurrencies,
});

export const useMunzenCurrencies = () => {
  return useUnit({
    currencies: $munzenCurrencies,
    isLoading: fetchMunzenCurrenciesFx.pending,
    fetchCurrencies: fetchMunzenCurrenciesFx,
  });
};

fetchMunzenCurrenciesFx();
