name: Docker Image CI/CD

on:
  push:
    branches:
      - dev

jobs:
  docker:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:unstable
          build-args: |
            NEXT_PUBLIC_WALLET_CONNECT_CLOUD_PROJECT_ID=${{ secrets.NEXT_PUBLIC_WALLET_CONNECT_CLOUD_PROJECT_ID }}
            NEXT_PUBLIC_ANKR_ID=${{ secrets.NEXT_PUBLIC_ANKR_ID }}
            NEXT_PUBLIC_MIXPANEL_ID=${{ secrets.NEXT_PUBLIC_MIXPANEL_ID }}
            NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}
            NEXT_PUBLIC_TYPE=${{ secrets.NEXT_PUBLIC_TYPE }}
            NEXT_PUBLIC_GA_ID=${{ secrets.NEXT_PUBLIC_GA_ID }}
            NEXT_PUBLIC_PRESALE_URL=${{ secrets.NEXT_PUBLIC_PRESALE_URL }}
            NEXT_PUBLIC_SENTRY_DSN=${{ secrets.NEXT_PUBLIC_SENTRY_DSN }}
