name: Docker Image CI/CD

on:
  push:
    branches:
      - master
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        env:
          NEXT_PUBLIC_WALLET_CONNECT_CLOUD_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_WALLET_CONNECT_CLOUD_PROJECT_ID }}
          NEXT_PUBLIC_ANKR_ID: ${{ secrets.NEXT_PUBLIC_ANKR_ID }}
          NEXT_PUBLIC_MIXPANEL_ID: ${{ secrets.NEXT_PUBLIC_MIXPANEL_ID }}
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
        with:
          file: Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
